language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on
  - CODECOV_TOKEN="3594d1ef-eeac-4ba0-ad12-5d56bbabe918"

install: true

notifications:
  email: false

before_script:
  - go get -v
  - go get -u -v github.com/golang/lint/golint
  - go get -u -v honnef.co/go/tools/cmd/megacheck
  - go get -u -v github.com/fzipp/gocyclo

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go vet ./...
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)