language: go
go:
  - 1.12.x

env:
  - GO111MODULE=on

install: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -v
  - go get -v honnef.co/go/tools/cmd/megacheck
  - go get -v github.com/fzipp/gocyclo

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - megacheck ./...
  - gocyclo -over 19 $GO_FILES
  
after_success:
  - export CODECOV_TOKEN="3594d1ef-eeac-4ba0-ad12-5d56bbabe918"
  - bash <(curl -s https://codecov.io/bash)